package com.sample.myrules
//package 随便写，但是不可重名

import com.lgp.drools.pojo.Message
 
rule "Hello World"
    when
        $m : Message( status == Message.HELLO, $myMessage : message )
    then
        System.out.println( "rules.sample.drl begin" );
        System.out.println( $myMessage);
        $m.setMessage( "Goodbye world" );
        $m.setStatus( Message.GOODBYE );
        update( $m );
        System.out.println( "rules.sample.drl end" );
end


rule "goodbye World"
    when
        $m : Message( status = Message.GOODBYE, $myMessage : message )
    then
        System.out.println( "rules.sample.drl begin" );
        System.out.println( $myMessage);
       /* $m.setMessage( "Goodbye world" );
        $m.setStatus( Message.GOODBYE );
        update( $m );*/
        System.out.println( "rules.sample.drl end" );
end


rule "goodbye"
    when
        eval(true)
    then
        System.out.println( "执行了" );
end
